@startuml

class "**[[StructureDefinition-BloodPressure.html Blood Pressure]]**" as bp {
    identifier
    interpretation: code
    location: code
    position: code
    method: code
    exertion: code|quantity
    cuffType: code
    cuffSize: code
    consciousness: code
    tilt: integer
    cuffType: code
    cuffSize: code
    dateTime: instant|period
    comment: string
}

abstract class "Blood Pressure Value" as bpv {
    value: integer
    unit = mm[Hg]
    referenceRange: range
    interpretation: code
}

class "**Systolic BP**" as syst
class "**Diastolic BP**" as diast
class "Mean Arterial Pressure" as mabp
class "Pulse Pressure" as pbp

class "Reference Range" as rr {
    low : integer
    high: integer
    age: range
}

class "Body Weight" as bw
Note right of bw
necessary to
interpret
the measurement
end Note
class "Medication" as med
class "Author" as a
class "Performer" as p
class "Subject" as s
Note left of s
normally
the patient
end Note

bpv <|-up- syst
bpv <|-up- diast
bpv <|-up- mabp
bpv <|-up- pbp
bpv "1" *-left- "1" rr

bp -right- "0..1" a
bp -right- "0..1" p
bp -left- "1" s
bp -- bw
bp -right- "0..*" med

bp *-- "1" syst
bp *-- "0..1" diast
bp *-- mabp
bp *-- pbp

@enduml