@startmindmap

skinparam svgDimensionStyle false

title Blood Pressure related Concepts to be considered

legend
Legend:
<img icon_modifier_extension_complex.png> relevant context details
<img icon_page_n_i.gif> addt'l information
end legend

+ **Blood** \n**Pressure**
--[#ff8] value
---[#fcc] systolic
----[#cff] DT: integer
-----_ range: 0-400
----[#fcc] reference range
-----_ range: 0-400
-----_ age: integer
---[#fcc] diastolic
----[#cff] DT: integer
-----_ range: 0-400
-----_ age: integer
----[#fcc] reference range
-----_ range: 0-400
---[#fcc] meanArterialPressure
----[#cff] DT: integer
-----_ range: 60-100
---- duration
-----[#cff] DT: code
------_ 1h
------_ 8h
------_ 10h
------_ 12h
------_ 24h
---- calculation
-----[#cff] DT: code
------_ ballanced
------_ algorithm
----[#fcc] reference range
---[#fcc] pulsePressure
----[#cff] DT: integer
-----_ range: 0-1000
----[#fcc] reference range
---[#fcc] duration of measurement
----[#cff] DT: code
-----_ spot
-----_ 1h
-----_ 8h
-----_ 10h
-----_ 12h
-----_ 24h
---[#fcc] unit
----[#cff] DT: code
-----_ mmHg
---[#fcc] reference range
----_ age: integer
----_ gender: code
---[#fcc] interpretation
----[#cff] DT: code
-----_ critical low
-----_ low
-----_ normal
-----_ high
-----_ critical high

-- other relevant concepts
--- <img icon_modifier_extension_complex.png> medication
----_ influences the results \nof the measurement
--- body weight
----_ relevant for a correct interpretation

++[#ff8] administrative
+++[#fcc] identifier
+++[#fcc] dateTime
++++[#cff] DT: instant | period
+++[#fcc] encounter

+++[#88f] involved persons
++++[#88f] subject
+++++_ age
+++++_ gender
++++[#88f] author
++++[#88f] performer

++[#ff8] protocol
+++[#ff8] location
++++[#cff] DT: code
+++++_ arm
+++++_ wrist
+++++_ ankle
+++++_ finger
+++++_ toe
+++[#ff8] <img icon_modifier_extension_complex.png> position
++++[#cff] DT: code
+++++_ sitting
+++++_ standing
+++++_ reclining
+++++_ lying
++++++_ lying on back
++++++_ lying with tilt to left
+++[#ff8] tilt (degree)
++++[#cff] DT: integer
+++[#ff8] <img icon_modifier_extension_complex.png> method
++++[#cff] DT: code
+++[#ff8] <img icon_modifier_extension_complex.png> exertion
++++[#cff] DT: code
++++[#cff] DT: PQ
+++++_ Watts
+++[#ff8] aspiration
++++_ expiration
++++_ inspiration
+++[#ff8] event
++++_ normal
++++_ stressed by someone/thing
+++++_ physician
+++++_ bear/tiger/snake
+++[#ff8] <img icon_page_n_i.gif> cuff type
++++[#cff] DT: code
+++[#ff8] <img icon_modifier_extension_complex.png> cuff size
++++[#cff] DT: code/integer
+++[#ff8] consciousness
++++[#cff] DT: code
+++++_ awake
+++++_ unconscious
+++++_ sleeping
+++[#ff8] <img icon_modifier_extension_complex.png> anaesthesia
++++[#cff] DT: code
+++++_ before
+++++_ during
+++++_ after

++[#ff8] comment
+++[#cff] DT: text

@endmindmap