@startuml

title BP Profile(s) in the Vital Sign Hierarchy

class "Observation" as obs {
    status: code
    category: code
    code: code
    observationDate: instant|period
}

class "Vital Sign" as vs {
    category: code = vital-sign
}

class "**(General) Blood Pressure**" as bp {
    category: code = blood-pressure
    systolicBP: positiveInt
    diastolicBP: positiveInt
    meanArterialBP: positiveInt
    pulseBP: positiveInt
    exertion: quantity
    position: code
    consciousness: code
    interpretation: code
    ...
}

obs <|-- vs
obs <|-- bp 


class "Body Weight" as bw {
    category: code = body-weight
}

class "Medication" as medic 

class "Blood Pressure Spot" as bps {
    date: instant
}

class "Blood Pressure Panel" as bpp {

}

class "Blood Pressure Average" as bpa {
    datePeriod: Period
}

bpa "0..*" o-right-- "0..*" bps

class "Patient" as pat
class "Author" as aut

class "US Core Spot BP" as usbp1 
class "DE Core BP" as debp
vs <|-- bpp
vs <|-- bw

class "US Core Avg BP" as usbp2 

obs -right- pat : subject >
obs -left- aut : author >

bp <|-- bps
bp <|-- bpa

bpa <|-- usbp2

bps <|-- usbp1
bps <|-- debp
bps <|-- bpp

bp "0..*" ..right. "0..1" bw
bp .left.. "0..*" medic

class "DE KBV BP" as dekbvbp
class "DE MII BP" as demiibp
class "DE Standard BP for EHR" as deehrbp

debp <|-- dekbvbp
debp <|-- demiibp
debp <|-- deehrbp

@enduml