@startuml

class "Vital Sign" as vs {
    status: code
    category: code = vital-sign
    code: code
    observationDate: instant|period
}

class "**Blood Pressure**" as bp {
    category: code = vital-sign-bp
    systolicBP: positiveInt
    diastolicBP: positiveInt
    meanArterialBP: positiveInt
    pulseBP: positiveInt
    exertion: quantity
    position: code
    interpretation: code
    ...
}

class "Body Weight" as bw {
    category: code = vital-sign-bw
}

class "Medication" as medic 

class "Blood Pressure Spot" as bps {
    date: instant
}

class "Blood Pressure 24h Average" as bpa {
    datePeriod: Period
}

class "Patient" as pat
class "Author" as aut

class "US Core BP" as usbp 
class "DE Core BP" as debp
vs <|-- bp
vs <|-- bw

vs -right- pat : subject >
vs -- aut : author >

bp <|-- bps
bp <|-- bpa

bps <|-- usbp
bps <|-- debp

bp "0..*" ..left. "0..1" bw
bp .right.. "0..*" medic

class "DE KBV BP" as dekbvbp
class "DE MII BP" as demiibp
class "DE Standard BP for EHR" as deehrbp

debp <|-- dekbvbp
debp <|-- demiibp
debp <|-- deehrbp

@enduml