@startuml

package "Core (de-identified)" as pkg0 {
}

package "Identified Core" as pkg0a {

}

package "US Core" as pkg0us {
}

package "DE Core" as pkg0de {
}

package "Vital Sign Base (Advanced)" as pkg1 {
}

pkg1 --> pkg0a : derive

package "Vital Sign Panel" as pkg1a {

}

pkg1 "1..*" --o "0..*" pkg1a : compose

package "Blood Pressure" as pkg2 {
}

package "Body Weight" as pkg3 {
}
package "Body Height" as pkg4 {
}

package "US Vital Sign Base (Advanced)" as pkg1us {
}

package "US Vital Sign Panel" as pkg1usA {

}

pkg1us "1..*" --o "0..*" pkg1usA : compose
pkg1a --> pkg1usA : derive

package "US Blood Pressure" as pkg2us {
}

package "DE Vital Sign Base (Advanced)" as pkg1de {
}

package "DE Blood Pressure" as pkg2de {
}

pkg0 --> pkg0us : derive

pkg1 --> pkg1us : derive
pkg1 --> pkg1de : derive

pkg2 --> pkg2us : derive
pkg2 --> pkg2de : derive

pkg1 -down-> pkg0 : derive
pkg1 -down-> pkg2 : derive
pkg1 -down-> pkg3 : derive
pkg1 -down-> pkg4 : derive

pkg1us --> pkg0us : include
pkg1de --> pkg0de : include

pkg2us --> pkg1us : include
pkg2de --> pkg1de : include

pkg1usA --> pkg0us : include


@enduml